[build]
builder = "nixpacks"

[deploy]
startCommand = "cd server && go run main.go"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "web" 